apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
data:
  username: YWRtaW4=
  passphrase: YWRtaW4=

---

  apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      istio-injection: enabled
    name: istio-demo
  