apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
spec:
  selector:
    matchLabels:
      app: student-api
  replicas: 2
  template: 
    metadata:
      labels:
        app: student-api
    spec:
      containers:
      - name: student-api
        image: mikaelvg/student-api:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: student-api
spec:
  selector:
    app: student-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31000      
      protocol: TCP
      name: http
