pipeline {

    environment {
        studentRegistry = "mikaelvg/crud-with-api-testing"
        registryCredential = 'dockerhub'
     }

    agent any
    stages {
        stage ('Repo') {
        
            steps {
                
                slackSend channel: 'allteams', color: 'good', message: 'Hello there', teamDomain: 'devkinetics'
                
            }
        }
    }

}
