pipeline {

    environment {
        studentRegistry = "mikaelvg/crud-with-api-testing"
        registryCredential = 'dockerhub'
     }

    agent any
    stages {
        stage ('Repo') {
        
            steps {
                
                slackSend channel: 'allteams', color: 'good', message: 'started ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)', teamDomain: 'devkinetics'
                
            }
        }


}
